name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          path: pr-branch

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ⚖️ Compare versions
        id: compare
        run: |
          PR_VERSION=$(node -p "require('./pr-branch/package.json').version")
          MAIN_VERSION=$(node -p "require('./main-branch/package.json').version")

          if [ "$PR_VERSION" == "$MAIN_VERSION" ]; then
            echo "::error::Version must be updated, matches default branch version of $MAIN_VERSION"
            exit 1
          else
            echo "::notice::Version check passed, PR version ($PR_VERSION) is different from default branch version ($MAIN_VERSION)."
          fi
